// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_lB2V6mg_sAQbGNAGJbaau9kcq1CDHH4',
    appId: '1:1030343360675:web:0ff554d90824298561bf16',
    messagingSenderId: '1030343360675',
    projectId: 'whales-fc802',
    authDomain: 'whales-fc802.firebaseapp.com',
    storageBucket: 'whales-fc802.appspot.com',
    measurementId: 'G-VN9YFP1PC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCarBUs9RFr-V0tsoSjSH3WE3kr996iQsc',
    appId: '1:1030343360675:android:29706028b894348561bf16',
    messagingSenderId: '1030343360675',
    projectId: 'whales-fc802',
    storageBucket: 'whales-fc802.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC_BNSNyLG97EgjTrphw7mFl-VaiiFZv0',
    appId: '1:1030343360675:ios:1a6e3b79a646bdf861bf16',
    messagingSenderId: '1030343360675',
    projectId: 'whales-fc802',
    storageBucket: 'whales-fc802.appspot.com',
    androidClientId: '1030343360675-c9u04d07qpm1u8jpu79t7k2d7l6etc9h.apps.googleusercontent.com',
    iosClientId: '1030343360675-j7f1arnvvfmaacod5jlvlfomor8kfeim.apps.googleusercontent.com',
    iosBundleId: 'com.offeringmarketplace.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC_BNSNyLG97EgjTrphw7mFl-VaiiFZv0',
    appId: '1:1030343360675:ios:1a6e3b79a646bdf861bf16',
    messagingSenderId: '1030343360675',
    projectId: 'whales-fc802',
    storageBucket: 'whales-fc802.appspot.com',
    androidClientId: '1030343360675-c9u04d07qpm1u8jpu79t7k2d7l6etc9h.apps.googleusercontent.com',
    iosClientId: '1030343360675-j7f1arnvvfmaacod5jlvlfomor8kfeim.apps.googleusercontent.com',
    iosBundleId: 'com.offeringmarketplace.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_lB2V6mg_sAQbGNAGJbaau9kcq1CDHH4',
    appId: '1:1030343360675:web:f576e2674cfdb6b461bf16',
    messagingSenderId: '1030343360675',
    projectId: 'whales-fc802',
    authDomain: 'whales-fc802.firebaseapp.com',
    storageBucket: 'whales-fc802.appspot.com',
    measurementId: 'G-SWDKM9RHPD',
  );

}